version: "3.8"
services:

  portainer:
    container_name: Portainer
    hostname: portainer
    image: portainer/portainer-ee:latest #Image from DockerHub
    restart: always
    ports:
      - 443:9443
    networks:
      - avb
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  phpmyadmin:
    container_name: phpMyAdmin
    hostname: phpmyadmin
    image: lscr.io/linuxserver/phpmyadmin:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 81:80
    networks:
      - avb
    volumes:
      - phpmyadminvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PMA_ARBITRARY=1

  mariadb:
    container_name: MariaDB
    hostname: mariadb
    image: lscr.io/linuxserver/mariadb:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 3006:3006
    networks:
      - avb
    volumes:
      - mariadbvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=CHANGETHIS

  homepage:
    container_name: Homepage
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest #Image from GitHub
    restart: always
    ports:
      - 3000:3000
    networks:
      - avb
    volumes:
      - homepagevol:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nextcloud:
    container_name: Nextcloud
    hostname: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 444:443
    networks:
      - avb
    volumes:
      - nextcloudvol:/config
      - nextcloudvol:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  teamspeak:
    container_name: Teamspeak
    hostname: teamspeak
    image: ertagh/teamspeak3-server:arm64v8-latest-box #Teamspeak Server image specific for ARM64v8 Devices #Image from DockerHub
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    networks:
      - avb
    volumes:
      - tsvol:/var/ts3server
    environment:
      - TS3SERVER_LICENSE=accept

  grafana:
    container_name: Grafana
    hostname: grafana
    image: grafana/grafana-enterprise #Image from DockerHub
    restart: unless-stopped
    ports:
      - 3010:3000
    networks:
      - avb
    volumes:
      - grafanavol:/var/lib/grafana
    links:
     - influxdb
  
  influxdb:
    container_name: InfluxDB
    hostname: influxdb
    image: influxdb:latest #Image from DockerHub
    restart: always
    ports:
      - 8086:8086
    networks:
      - avb
    volumes:
      - influxdbvol:/var/lib/influxdb
      - influxdbvol:/etc/influxdb2
    security_opt:
      - no-new-privileges:true

  pihole:
    container_name: PiHole
    hostname: pihole
    image: pihole/pihole:latest #Image from DockerHub
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    networks:
      - avh
      - avb
    volumes:
      - piholevol:/etc/pihole
      - piholevol:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Berlin
    #cap_add:
     # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

  netboot:
    container_name: NetbootXYZ
    hostname: netboot
    image: lscr.io/linuxserver/netbootxyz:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 3020:3020
      - 69:69/udp
      - 8080:8080
    networks:
      - avb
    volumes:
      - netbootvol:/config
      - netbootvol:/assets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MENU_VERSION=
      - PORT_RANGE=30000-30010
      - NGINX_PORT= 8080
      - WEB_APP_PORT= 3020

volumes:
  portainer:
  phpmyadminvol:
  mariadbvol:
  homepagevol:
  nextcloudvol:
  tsvol:
  grafanavol:
  influxdbvol:
  piholevol:
  netbootvol:

networks:
  avb: #Bridge Network
    driver: bridge
  avh: #Host Network 
    driver: host
  avn: #Isolation Network
    driver: none