# // Overview of this file
# // Following Services and what they do:

#1 Portainer for managing Docker
#2 phpMyAdmin for managing mysql/mariadb databases
#3 mariadb for storing data
#4 homepage for collecting the hosted services and making them easily accessible
#5 nextcloud for storing files like pictures, documents, etc.
#6 teamspeak for providing a voice chat server running with minimal resources
#7 grafana for Visualising data in Dashboards
#8 influxdb for collecting data to provide to grafana
#9 pihole to block ads, log network data and provide a pxe connection
#10 netbootxyz to provide a pxe boot server

version: "3.8"
services:

  portainer:
    container_name: Portainer
    hostname: portainer
    image: portainer/portainer-ee:latest #Image from DockerHub
    restart: always
    ports:
      - 445:9443
    networks:
      - avb
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  phpmyadmin:
    container_name: phpMyAdmin
    hostname: phpmyadmin
    image: lscr.io/linuxserver/phpmyadmin:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 83:80
    networks:
      - avb
    volumes:
      - phpmyadminvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PMA_ARBITRARY=1

  mariadb:
    container_name: MariaDB
    hostname: mariadb
    image: lscr.io/linuxserver/mariadb:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 3006:3006
    networks:
      - avb
    volumes:
      - mariadbvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=CHANGETHIS

  homepage:
    container_name: Homepage
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest #Image from GitHub
    restart: always
    ports:
      - 3000:3000
    networks:
      - avb
    volumes:
      - homepagevol:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/Docker/Images/Backgrounds:/app/public/images
      - $HOME/Docker/Images/Icons:/app/public/icons

  nextcloud:
    container_name: Nextcloud
    hostname: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 444:443
    networks:
      - avb
    volumes:
      - nextcloudvol:/config
      - nextcloudvol:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  teamspeak:
    container_name: Teamspeak
    hostname: teamspeak
    image: ertagh/teamspeak3-server:arm64v8-latest-box #Teamspeak Server image specific for ARM64v8 Devices #Image from DockerHub
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    networks:
      - avb
    volumes:
      - tsvol:/var/ts3server
    environment:
      - TS3SERVER_LICENSE=accept

  grafana:
    container_name: Grafana
    hostname: grafana
    image: grafana/grafana-enterprise #Image from DockerHub
    restart: unless-stopped
    ports:
      - 3010:3000
    networks:
      - avb
    volumes:
      - grafanavol:/var/lib/grafana
    links:
     - influxdb
  
  influxdb:
    container_name: InfluxDB
    hostname: influxdb
    image: influxdb:latest #Image from DockerHub
    restart: always
    ports:
      - 8086:8086
    networks:
      - avb
    volumes:
      - influxdbvol:/var/lib/influxdb
      - influxdbvol:/etc/influxdb2
    security_opt:
      - no-new-privileges:true

  pihole:
    container_name: PiHole
    hostname: pihole
    image: pihole/pihole:latest #Image from DockerHub
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - 82:80/tcp
    networks:
      - avb
    volumes:
      - piholevol:/etc/pihole
      - dnsmasqvol:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Berlin
    #cap_add:
     # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

  netboot:
    container_name: NetbootXYZ
    hostname: netboot
    image: lscr.io/linuxserver/netbootxyz:latest #Image from LinuxServer.io
    restart: always
    ports:
      - 3020:3020
      - 69:69/udp
      - 8080:8080
    networks:
      - avb
    volumes:
      - netbootvol:/config
      - netbootvol:/assets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MENU_VERSION=
      - PORT_RANGE=30000-30010
      - NGINX_PORT= 8080
      - WEB_APP_PORT= 3020

  nginxproxymanager:
    container_name: Nginx-Proxy-Manager
    hostname: nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - avb
    volumes:
      - nginxproxyvol:/data
      - nginxproxyvol:/etc/letsencrypt

volumes:
  portainer:
  phpmyadminvol:
  mariadbvol:
  homepagevol:
  nextcloudvol:
  tsvol:
  grafanavol:
  influxdbvol:
  piholevol:
  dnsmasqvol:
  netbootvol:
  nginxproxyvol:

networks:
  avb: #Bridge Network
    driver: bridge
  avn: #Isolation Network
    driver: none