version: 3.8
services:
  servicename:
    container_name: containername
    hostname: containernetname
    image: imagename:tag
    restart: always
    ports:
      - 80:80
    networks:
      - specifiednetwork
    volumes:
      - volumename:/containerpath
    environment:
      - name=value
    depends_on:
      - servicename

volumes:
  volumename:

networks:
  avb: #Bridge Network
    driver: bridge
  avn: #Isolation Network
    driver: none