version: 3.8
services:
  servicename:
    container_name: containername
    hostname: containernetname
    image: imagename:tag
    restart: always
    ports:
      - 80:80
    networks:
      - specifiednetwork
    volumes:
      - volumename:/containerpath
    environment:
      - name=value

volumes:
  volumename:
    driver: overlay2

networks:
  avb: #Bridge Network
    driver: bridge
  avh: #Host Network 
    driver: host
  avn: #Isolation Network
    driver: none