version: "3.8"
services:

  portainer:
    container_name: Portainer
    hostname: portainer
    image: portainer/portainer-ee:latest
    restart: always
    ports:
      - 9443:9443
    networks:
      - avb
    volumes:
      - portainervol:/data
      - /var/run/docker.sock:/var/run/docker.sock

  homepage:
    container_name: Homepage
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - avb
    volumes:
      - homepagevol:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/Docker/Images/Backgrounds:/app/public/images
      - $HOME/Docker/Images/Icons:/app/public/icons

  pihole:
    container_name: PiHole
    hostname: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - 53:53
      - 53:53/udp
      - 80:80
    networks:
      - avb
    volumes:
      - piholevol:/etc/pihole
      - dnsmasqvol:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Berlin

  plex:
    container_name: Plex
    hostname: plex
    image: lscr.io/linuxserver/plex:latest
    restart: always
    networks:
      - avb
    network_mode: host
    volumes:
      - plexvol:/config
      - plexvol:/tv
      - plexvol:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker

  jackett:
    container_name: Jackett
    hostname: jackett
    image: lscr.io/linuxserver/jackett:latest
    restart: always
    ports:
      - 9117:9117
    networks:
      - avb
    volumes:
      - jackettvol:/config
      - qbittorrentvol:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true

  sonarr:
    container_name: Sonarr
    hostname: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: always
    ports:
      - 8989:8989
    networks:
      - avb
    volumes:
      - sonarrvol:/config
      - plexvol:/tv
      - qbittorrentvol:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  radarr:
    container_name: Radarr
    hostname: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: always
    ports:
      - 7878:7878
    networks:
      - avb
    volumes:
      - radarrvol:/config
      - plexvol:/movies
      - qbittorrentvol:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  qbittorrent:
    container_name: qBittorrent
    hostname: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: always
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - specifiednetwork
    volumes:
      - qbittorrentvol:/config
      - qbittorrentvol:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

  bazarr:
    container_name: Bazarr
    hostname: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: always
    ports:
      - 6767:6767
    networks:
      - avb
    volumes:
      - bazarrvol:/config
      - plexvol:/tv
      - plexvol:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  overseerr:
    container_name: Overseerr
    hostname: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: always
    ports:
      - 5055:5055
    networks:
      - avb
    volumes:
      - overseerrvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  mariadb:
    container_name: MariaDB
    hostname: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart: always
    ports:
      - 3306:3306
    networks:
      - avb
    volumes:
      - mariadbvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=CHANGETHIS!

  influxdb:
    container_name: InfluxDB
    hostname: influxdb
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086
    networks:
      - avb
    volumes:
      - influxdbvol:/var/lib/influxdb
      - influxdbvol:/etc/influxdb2
    security_opt:
      - no-new-privileges:true

  nextcloud:
    container_name: Nextcloud
    hostname: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    restart: always
    ports:
      - 443:443
    networks:
      - avb
    volumes:
      - nextcloudvol:/config
      - nextcloudvol:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

  phpmyadmin:
    container_name: phpMyAdmin
    hostname: phpmyadmin
    image: lscr.io/linuxserver/phpmyadmin:latest
    restart: always
    ports:
      - 90:80
    networks:
      - avb
    volumes:
      - phpmyadminvol:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PMA_ARBITRARY=1

  teamspeak:
    container_name: Teamspeak
    hostname: teamspeak
    image: ertagh/teamspeak3-server:arm64v8-latest-box
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    networks:
      - avb
    volumes:
      - teamspeakvol:/var/ts3server
    environment:
      - TS3SERVER_LICENSE=accept

  netbootxyz:
    container_name: NetbootXYZ
    hostname: netbootxyz
    image: lscr.io/linuxserver/netbootxyz:latest
    restart: always
    ports:
      - 3010:3000
      - 69:69/udp
      - 95:80
    networks:
      - avb
    volumes:
      - netbootvol:/config
      - netbootvol:/assets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MENU_VERSION=
      - PORT_RANGE=30000:30010
      - SUBFOLDER=/
      - NGINX_PORT=95
      - WEB_APP_PORT=3010

  grafana:
    container_name: Grafana
    hostname: grafana
    image: grafana/grafana-enterprise
    restart: always
    ports:
      - 3020:3000
    networks:
      - specifiednetwork
    volumes:
      - grafanavol:/var/lib/grafana
    links:
     - influxdb

volumes:
portainervol:
homepagevol:
piholevol:
dnsmasqvol:
plexvol:
jackettvol:
sonarrvol:
radarrvol:
qbittorrentvol:
bazarrvol:
overseerrvol:
doplarrvol:
mariadbvol:
influxdbvol:
nextcloudvol:
phpmyadminvol:
teamspeakvol:
netbootvol:
grafanavol:

networks:
  avb: #Bridge Network
    driver: bridge
  avn: #Isolation Network
    driver: none